Dispacth campaing in tracksale
sympla/the-broken-tusk pull request #1
Opened 2020-09-01 20:49 UTC by lucascamp

2020-09-02 16:17 UTC, guilhermecrcio commented on src/Exception/RequestFailed.php
> +    public function __construct($message, $statusCode, ResponseInterface $response)
Faltou o comentário

2020-09-02 16:17 UTC, guilhermecrcio commented on src/Exception/RequestFailed.php
> +    /** @var ResponseInterface $response */
Não precisa ter o nome da variável apenas o tipo

2020-09-02 16:17 UTC, guilhermecrcio commented on src/Exception/RequestFailed.php
> +    /** @var int $statusCode */
Não precisa ter o nome da variável apenas o tipo

2020-09-02 16:18 UTC, guilhermecrcio commented on src/Helpers/BuildUrl.php
> +use ReflectionException;
Por boas práticas classes nativas do php não precisam do use apenas usar com \ dentro do código exemplo: new \ReflectionClass

2020-09-02 16:18 UTC, guilhermecrcio commented on src/Helpers/BuildUrl.php
> +use ReflectionClass;
Por boas práticas classes nativas do php não precisam do use apenas usar com \ dentro do código exemplo: new \ReflectionClass

2020-09-02 16:19 UTC, guilhermecrcio commented on src/Helpers/BuildUrl.php
> +    public static function getUrlByRoute(string $route): string
faltou comentário sobre o que o método faz e também não criar métodos estáticos, lembrar que depois será escrito o teste unitário

2020-09-02 16:19 UTC, guilhermecrcio commented on src/Helpers/BuildUrl.php
> +    private static function routeExists(string $route): bool
faltou comentário sobre o que o método faz e também não criar métodos estáticos, lembrar que depois será escrito o teste unitário

2020-09-02 16:21 UTC, guilhermecrcio commented on src/Configuration/Http.php
> +class Http
Acho que para configurações do projeto seria melhor usar um array ou yml

2020-09-02 16:21 UTC, guilhermecrcio commented on src/Configuration/Routes.php
> +class Routes
Acho que para configurações do projeto seria melhor usar um array ou yml

2020-09-02 16:21 UTC, guilhermecrcio commented on src/Request/DispatchCampaign.php
> +        $this->token = $token;
Faltou declarar o atributo

2020-09-02 16:22 UTC, guilhermecrcio commented on src/Request/DispatchCampaign.php
> +    public function sendDispatchRequest(string $campaign_id, string $user_name, string $user_email): ResponseInterface
Faltou o comentário da classe e os demais parâmetros

2020-09-02 16:22 UTC, guilhermecrcio commented on src/Request/DispatchCampaign.php
> +        $client = new Client(['headers' => ['Authorization' => 'Bearer '.$this->token, 'Content-Type' => 'application/json']]);
Usar o método getGuzzleInstance

2020-09-02 16:23 UTC, guilhermecrcio commented on src/Request/DispatchCampaign.php
> +    protected function emailValidate(string $email)
Faltou comentário do método

2020-09-02 16:23 UTC, guilhermecrcio commented on src/Request/DispatchCampaign.php
> +    {
Faltou comentário do método

2020-09-02 16:24 UTC, guilhermecrcio commented on src/Request/DispatchCampaign.php
> +    protected function getJsonToSend(string $user_name, string $user_email): string
Faltou os parâmetros nos comentários

2020-09-02 16:25 UTC, guilhermecrcio commented on src/Exception/JsonException.php
> +use Throwable;
Não está sendo usado

2020-09-02 16:25 UTC, guilhermecrcio commented on src/Exception/RequestFailed.php
> +use Exception;
Por boas práticas classes nativas do php não precisam do use apenas usar com \ dentro do código exemplo: new \ReflectionClass

2020-09-02 16:26 UTC, guilhermecrcio commented on src/Exception/JsonException.php
> +use Exception;
Por boas práticas classes nativas do php não precisam do use apenas usar com \ dentro do código exemplo: new \ReflectionClass

2020-09-02 16:26 UTC, guilhermecrcio commented on src/Exception/InvalidRouteException.php
> +use Exception;
Por boas práticas classes nativas do php não precisam do use apenas usar com \ dentro do código exemplo: new \ReflectionClass

2020-09-02 16:26 UTC, guilhermecrcio commented on src/Exception/IncorrectTypeException.php
> +namespace RDStation\Exception;
Namespace errado

2020-09-02 16:32 UTC, guilhermecrcio commented on src/Exception/InvalidRouteException.php
> +class InvalidRouteException extends Exception
Não achei onde ela está sendo utilizada

2020-09-02 16:33 UTC, guilhermecrcio commented on src/Exception/JsonException.php
> +class JsonException extends Exception
Não achei onde está sendo utilizada

2020-09-02 16:33 UTC, guilhermecrcio commented on src/Exception/RequestFailed.php
> +class RequestFailed extends Exception
Não achei onde está sendo utilizada

2020-09-02 22:32 UTC, guilhermecrcio requested changes

2020-09-02 22:32 UTC, guilhermecrcio commented on src/Request/DispatchCampaign.php
> +use ReflectionException;
Não fazer use me classes nativas

2020-09-03 13:48 UTC, guilhermecrcio approved these changes

2020-09-03 13:49 UTC, guilhermecrcio requested changes

2020-09-03 13:49 UTC, guilhermecrcio commented on src/Request/DispatchCampaign.php
> +        return BuildUrl::getUrlByRoute(Http::ROUTES['DISPATCH']) . '/' . $campaign_id . '/dispatch';
O método não é mais estático, criar um outro método que retorna uma instância do build url

2020-09-03 14:40 UTC, pedroigorsilva approved these changes

2020-09-03 14:40 UTC, merged